version: "3.8"

services:
    server:
        build: ./apps/server
        ports:
            - "${BACKEND_PORT}:${BACKEND_PORT}"
        environment:
            - NODE_ENV=production

    web:
        build: ./apps/web
        ports:
            - "80:3000"
        environment:
            - NODE_ENV=production
        depends_on:
            - server
